name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
<<<<<<< HEAD
    - uses: actions/checkout@v6
    - name: Use Node.js 20
      uses: actions/setup-node@v6
      with:
        node-version: 24
=======
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
>>>>>>> 40b2b8c (Initial commit)
    - run: npm ci
    - run: npm run lint
=======
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node -v
      - run: npm -v
      - run: ls -la

      - name: Install dependencies
        run: npm ci --verbose

      - run: npm run lint
>>>>>>> 128ccf8 (main.yaml)
